apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gardener-custom-metrics
    high-availability-config.resources.gardener.cloud/type: controller
  name: {{ .DeploymentName }}
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gardener-custom-metrics
      gardener.cloud/role: gardener-custom-metrics
      resources.gardener.cloud/managed-by: gardener
  template:
    metadata:
      labels:
        app: gardener-custom-metrics
        gardener.cloud/role: gardener-custom-metrics
        resources.gardener.cloud/managed-by: gardener
        networking.gardener.cloud/from-seed: allowed
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-runtime-apiserver: allowed
        networking.resources.gardener.cloud/to-all-shoots-kube-apiserver-tcp-443: allowed
        networking.gardener.cloud/to-apiserver: allowed
    spec:
      containers:
        - command:
            - ./gardener-custom-metrics
            - --secure-port=6443
            - --tls-cert-file=/var/run/secrets/gardener.cloud/tls/tls.crt
            - --tls-private-key-file=/var/run/secrets/gardener.cloud/tls/tls.key
            - --leader-election=true
            - --namespace=garden
            - --access-ip=$(POD_IP)
            - --access-port=6443
            - --log-level=75 # TODO: Andrey: P1: Reduce. Also, do we need logtostderr=true?
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: LEADER_ELECTION_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .ContainerImageName }}
          imagePullPolicy: IfNotPresent
          name: gardener-custom-metrics
          ports:
            - containerPort: 6443
              name: metrics-server
              protocol: TCP
          resources:
            requests:
              cpu: 80m
              memory: 800Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/gardener.cloud/tls
              name: gardener-custom-metrics-tls
              readOnly: true
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-gardener
              readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: gardener-custom-metrics-image-pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: gardener-custom-metrics
      terminationGracePeriodSeconds: 30
      volumes:
        - name: gardener-custom-metrics-tls
          secret:
            secretName: {{ .ServerSecretName }}
        - name: kube-api-access-gardener
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  expirationSeconds: 43200
                  path: token
              - configMap:
                  items:
                    - key: ca.crt
                      path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                      path: namespace
