apiVersion: v1
kind: Service
metadata:
  name: gardener-custom-metrics
  namespace: {{ .Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 443
      protocol: TCP
      targetPort: 6443
  publishNotReadyAddresses: true
  sessionAffinity: None # TODO: Andrey: P1: What affinity do we want?
  type: ClusterIP
  # This service intentionally does not contain a pod selector. As a result, KCM does not perform any endpoint management.
  # Endpoint management is instead done by the gardener-custom-metrics leader instance, which ensures a single endpoint,
  # directing all traffic to the leader.
