apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta2.custom.metrics.k8s.io
spec:
  service:
    name: gardener-custom-metrics
    namespace: {{ .Namespace }}
    port: 443
  group: custom.metrics.k8s.io
  version: v1beta2
  insecureSkipTLSVerify: true # TODO: Andrey: P1: Remove
  groupPriorityMinimum: 100
  versionPriority: 200
