apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    gardener.cloud/role: gardener-custom-metrics
    resources.gardener.cloud/managed-by: gardener
  name: gardener-custom-metrics
  namespace: {{ .Namespace }}
spec:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: gardener-custom-metrics
      gardener.cloud/role: gardener-custom-metrics
