apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app:  pvc-autoscaler
    gardener.cloud/role: pvc-autoscaler
  name: pvc-autoscaler
  namespace: garden
automountServiceAccountToken: false
