apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.resources.gardener.cloud/from-all-seed-scrape-targets-allowed-ports: '[{"port":8443,"protocol":"TCP"}]'
    networking.resources.gardener.cloud/from-world-to-ports: '[{"port":8443,"protocol":"TCP"}]' # TODO: Temporarily added for research access. Remove.
  labels:
    app:  pvc-autoscaler
    gardener.cloud/role: pvc-autoscaler
  name: pvc-autoscaler-metrics
  namespace: garden
spec:
  ports:
    - name: metrics
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app:  pvc-autoscaler
    gardener.cloud/role: pvc-autoscaler
  type: LoadBalancer  # TODO: Temporarily added for research access. Remove.
